# Generated by Django 6.0.6 on 2026-06-08 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('headscale_host', models.CharField(max_length=255)),
                ('headplane_host', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=128)),
                ('bootstrap_status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('bootstrapped', 'Bootstrapped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('desired_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='workers.worker')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
