# Generated by Django 6.0.6 on 2026-06-08 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('probed_at', models.DateTimeField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('healthy', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'tenant health records',
                'ordering': ['-probed_at'],
            },
        ),
    ]
