# Generated by Django 6.0.6 on 2026-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='bootstrap_output_ref',
            field=models.CharField(blank=True, default='', help_text='Reference to bootstrap output artifact (not raw keys).', max_length=255),
        ),
    ]
