# Generated by Django 6.0.6 on 2026-06-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_bootstrap_output_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="runtime_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("provisioning", "Provisioning"),
                    ("running", "Running"),
                    ("stopped", "Stopped"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
