# Generated by Django 6.0.6 on 2026-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="tenant_inventory",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
