# Generated by Django 6.0.6 on 2026-06-08 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('online', 'Online'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('enrollment_token_ref', models.CharField(blank=True, max_length=255)),
                ('custom_tags', models.JSONField(blank=True, default=list)),
                ('tailscale_node_id', models.CharField(blank=True, max_length=64)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='tenants.tenant')),
            ],
            options={
                'ordering': ['hostname', 'id'],
            },
        ),
    ]
