# Generated by Django 6.0.6 on 2026-06-08 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway', to='agents.agent'),
        ),
    ]
