# Generated by Django 6.0.6 on 2026-06-08 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0002_gateway_agent'),
        ('tenants', '0003_tenant_bootstrap_output_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64)),
                ('prefix', models.CharField(db_index=True, max_length=8)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
