# Generated by Django 6.0.6 on 2026-06-13 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_tenant_inventory'),
        ('gateways', '0003_enrollment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_new', models.BooleanField(default=True)),
                ('last_vuln_scan_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_hosts', to='gateways.gateway')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='GatewayMonitorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('monitored_cidrs', models.JSONField(default=list)),
                ('scan_strategy', models.CharField(choices=[('sequential', 'Sequential'), ('chunked', 'Chunked')], default='chunked', max_length=16)),
                ('chunk_count', models.PositiveIntegerField(default=4)),
                ('discover_interval_minutes', models.PositiveIntegerField(default=60)),
                ('vuln_rescan_days', models.PositiveIntegerField(default=7)),
                ('vuln_scan_enabled', models.BooleanField(default=False)),
                ('vuln_modules', models.JSONField(blank=True, default=list)),
                ('nuclei_enabled', models.BooleanField(default=False)),
                ('chunk_cursor', models.PositiveIntegerField(default=0)),
                ('last_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_policy', to='gateways.gateway')),
            ],
            options={
                'verbose_name': 'Gateway Monitor Policy',
                'verbose_name_plural': 'Gateway Monitor Policies',
            },
        ),
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('new_host', 'New Host')], db_index=True, default='new_host', max_length=32)),
                ('host_ip', models.GenericIPAddressField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_alerts', to='gateways.gateway')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField()),
                ('chunk_cidrs', models.JSONField(default=list)),
                ('host_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_snapshots', to='agents.agentcommand')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_snapshots', to='gateways.gateway')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, default='info', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('finding_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('found_at', models.DateTimeField()),
                ('discovered_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_findings', to='gateways.discoveredhost')),
            ],
            options={
                'ordering': ['-found_at', 'severity'],
            },
        ),
        migrations.AddConstraint(
            model_name='discoveredhost',
            constraint=models.UniqueConstraint(fields=('gateway', 'ip'), name='unique_gateway_host_ip'),
        ),
    ]
