# Generated by Django 6.0.6 on 2026-06-13 16:05

import gateways.monitoring_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0004_discoveredhost_gatewaymonitorpolicy_monitoralert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaymonitorpolicy',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gatewaymonitorpolicy',
            name='monitored_cidrs',
            field=models.JSONField(default=gateways.monitoring_policy.default_monitored_cidrs),
        ),
        migrations.AlterField(
            model_name='gatewaymonitorpolicy',
            name='scan_strategy',
            field=models.CharField(choices=[('rotating_chunks', 'Rotating chunks'), ('full_sweep', 'Full sweep')], default='rotating_chunks', max_length=16),
        ),
    ]
