# Generated by Django 6.0.6 on 2026-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0005_monitoring_policy_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredhost',
            name='vuln_scan_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaymonitorpolicy',
            name='vuln_parallel_workers',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
