# Generated by Django 6.0.6 on 2026-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0006_vuln_async_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewaymonitorpolicy',
            name='nuclei_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gatewaymonitorpolicy',
            name='vuln_rescan_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
