# Generated by Django 6.0.6 on 2026-06-08 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('online', 'Online'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('credential_ref', models.CharField(blank=True, help_text='Reference to rotatable agent credential (not plaintext).', max_length=255)),
                ('docker_reachable', models.BooleanField(default=False)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
