from __future__ import annotations

SUPPORTED_SCRIPT_NAMES = frozenset({"linux.sh", "gateway.sh"})

_LINUX_SCRIPT_HEADER = """#!/bin/sh
# Tailscale workspace client setup (generated by headscale-management)
set -e

LOGIN_SERVER="{login_server}"
AUTH_KEY=""
"""

_LINUX_SCRIPT_BODY = """
read_user_input() {
    prompt_text="$1"
    if [ -r /dev/tty ]; then
        printf "%s" "$prompt_text" > /dev/tty
        IFS= read -r REPLY < /dev/tty
        return $?
    fi
    printf "%s" "$prompt_text"
    IFS= read -r REPLY
}

connect_tailscale() {
    tailscale up \\
        --force-reauth \\
        --login-server="$LOGIN_SERVER" \\
        --authkey="$AUTH_KEY" \\
        --accept-routes \\
        --accept-dns
}

prompt_auth_key() {
    read_user_input "Enter workspace auth key: "
    AUTH_KEY="$(echo "$REPLY" | tr -d '[:space:]')"
}

prompt_auth_key
connect_tailscale
"""

_GATEWAY_SCRIPT_HEADER = """#!/bin/sh
# Tailscale gateway subnet router setup (generated by headscale-management)
set -e

LOGIN_SERVER="{login_server}"
AUTH_KEY=""
ADVERTISE_ROUTES=""
"""

_GATEWAY_SCRIPT_BODY = """
read_user_input() {
    prompt_text="$1"
    if [ -r /dev/tty ]; then
        printf "%s" "$prompt_text" > /dev/tty
        IFS= read -r REPLY < /dev/tty
        return $?
    fi
    printf "%s" "$prompt_text"
    IFS= read -r REPLY
}

connect_as_gateway() {
    tailscale up \\
        --force-reauth \\
        --login-server="$LOGIN_SERVER" \\
        --authkey="$AUTH_KEY" \\
        --advertise-routes="$ADVERTISE_ROUTES" \\
        --accept-dns \\
        --reset
}

prompt_auth_key() {
    read_user_input "Enter gateway auth key: "
    AUTH_KEY="$(echo "$REPLY" | tr -d '[:space:]')"
}

prompt_routes() {
    read_user_input "Enter comma-separated CIDR routes: "
    ADVERTISE_ROUTES="$(echo "$REPLY" | tr -d '[:space:]')"
}

prompt_auth_key
prompt_routes
connect_as_gateway
"""


def generate_linux_script(*, login_server: str) -> str:
    return _LINUX_SCRIPT_HEADER.format(login_server=login_server) + _LINUX_SCRIPT_BODY


def generate_gateway_script(*, login_server: str) -> str:
    return _GATEWAY_SCRIPT_HEADER.format(login_server=login_server) + _GATEWAY_SCRIPT_BODY


def generate_script(name: str, *, login_server: str) -> str:
    if name == "linux.sh":
        return generate_linux_script(login_server=login_server)
    if name == "gateway.sh":
        return generate_gateway_script(login_server=login_server)
    msg = f"Unsupported script name: {name}"
    raise ValueError(msg)
